### ISSUE TITLE
Encoding issue on story title

### ISSUE THREAD

**Issue by trbielec** [timho102003/NewsGPT#2]
Description:
The story title displays the “&amp;” encoding for the ampersand (&) character. The title reads “NVIDIA &amp; MediaTek” instead of the expected “NVIDIA & MediaTek”.

Steps to Reproduce:

	1.	Visit the provided URL (neotice.app).
	2.	Observe the title of the article about NVIDIA &amp; MediaTek’s collaboration.

Expected Result:
The title should display as “NVIDIA & MediaTek Reportedly Working On Arm Based CPUs With TSMC’s CoWoS Packaging.”

Actual Result:
The title displays as “NVIDIA &amp; MediaTek Reportedly Working On Arm Based CPUs With TSMC’s CoWoS Packaging.”

![image](https://github.com/timho102003/NewsGPT/assets/663001/755ba0fe-4d07-4cba-8955-74a74274ca5a)

**Comment by timho102003** [comment]
Thank you for your feedback. We greatly appreciate it. We will carefully look into the issue you have raised and work on fixing it as soon as possible.

**Comment by timho102003** [comment]
Hi @trbielec, we fixed the issue. Thanks again for your feedback
